#docker-compose.yml
services:

  service_django_dev:
    build:
      context: ../django_service_1
      dockerfile: docker/Dockerfile
    container_name: service_django_dev
    profiles: ["development"]
    volumes:
      - teste_django_db_data:/app/db
      - static_volume:/app/static
      - ../django_service_1:/core  # Mount source code for hot reload
    command: sh -c "pip freeze > /core/requirements/all_requirements.freeze.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ../.env
    ports:
      - "8011:8000"

  nginx_dev:
    image: nginx
    profiles: ["development"]
    ports:
      - "80:80"
    volumes:
      - ./nginx_config_files/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static:ro
    depends_on:
      - service_django_dev
  
# Volumes garante que os dados do banco de dados sejam mantidos persistentemente
volumes:
  # Declaração explícita do volume nomeado
  teste_django_db_data:
  static_volume:
  postgres_data: 